### PR TITLE
MAINT: Switch to CircleCI deployment

### PR DESCRIPTION
**Pull request by larsoner**
This will switch all doc building to CircleCI. This should simplify the CI structure as all NumpyDoc + examples should effectively be checked by this one build.

Eventually the structure will be:

- stable (0.2): `mne.tools/mne-nirs/stable/index.html`
- dev: `mne.tools/mne-nirs/dev/index.html`
- other versions (will become available once a 0.3 release is made is made): `mne.tools/mne-nirs/0.2/index.html`
- legacy: `mne.tools/mne-nirs/index.html` will redirect to stable

@rob-luke if you're on board with this, I'll iterate and mess with `gh-pages` until this is all working make this work.

### CODE REVIEW

**Comment by larsoner** [comment]
Some small tweaks to make it more MNE-Python like along the way:

https://2253-254026779-gh.circle-artifacts.com/0/html/index.html

The "warning this is dev" should appear because this will be loaded (adapted from MNE-Python's): https://mne.tools/mne-nirs/versionwarning.js

**Comment by rob-luke** [comment]
Awesome @larsoner. I appreciate you bringing MNE-NIRS into alignment with MNE-Python. I value the reduction in administrative/management overhead that this will achieve. Merge when you are happy.

**Comment by larsoner** [comment]
FYI this probably won't work the first time around. I'll probably push some commits directly to `main` to get it to work. Usually some SSH key stuff needs to be done. Looking at the CircleCI settings, though, it might already be there!

**Comment by larsoner** [comment]
Okay, looks like it's working

https://mne.tools/mne-nirs/dev/auto_examples/index.html

**Comment by rob-luke** [comment]
I just clicked around the docs and everything is looking good to me. Thanks @larsoner

**Pull request merged**
