### PR TITLE
Can we just use MNE in requirements?

### PR DESCRIPTION
**Pull request by rob-luke**
Issue #160

### CODE REVIEW

**Comment by rob-luke** [comment]
Need to rebase once paths are fixed.

**Comment by rob-luke** [comment]
@larsoner do you foresee any issues with me going this sparse with the requirements and environment files?

**Comment by agramfort** [comment]
installing mne-python like this will only give you numpy, scipy and matplotlib. You will not have any 3D support.

**Comment by rob-luke** [comment]
Thanks @agramfort that is very relevant for me to know because MNE-nirs provides some nirs specific 3D plots.

It seems I shouldn't go bare minimum then. I will add the 3D libraries back in.

**Comment by rob-luke** [comment]
Thanks for point this out @agramfort, I know see that in the CI tests the 3d plots are being skipped due to the `@requires_pysurfer` line.

image

@larsoner I am now struggling to see the middle ground here. I find the most helpful part of having the environment.yml file is that new users load that in to anaconda and they are instantly ready to go, which makes me think keeping the full file will make my life easier. Also this makes it easy for me to keep in sync with MNE. But as you mentioned, this is probably overkill for CI testing. Is it ok to leave as is for now and revisit this later?

**Comment by larsoner** [comment]
Yeah it should be fine to leave it

**Comment by rob-luke** [comment]
Thanks @larsoner. I would like to optimise these still (maybe when I've got a bit more time) so I will leave the issue open.

**Pull request closed without merging**
