### PR TITLE
[BUG] Fix moved `ContainsMixin`

### PR DESCRIPTION
**Pull request by alexrockhill**
Fixes `ContainsMixin` moved to `mne.io.meas_info`.

### CODE REVIEW

**Comment by alexrockhill** [comment]
Looks like the tests passed, it sounds like @rhoechenburg wanted to make an mne-bids release once this is merged.

**Comment by larsoner** [comment]
Thanks @alexrockhill 

@rob-luke we should cut a point release. I can do it Monday

**Comment by rob-luke** [comment]
Thanks @alexrockhill and @larsoner 

I can cut a new point release now and test out the new instructions/steps. I'll let you know if I get stuck or it's done.

**Comment by rob-luke** [comment]
Release done @alexrockhill @larsoner

**Comment by larsoner** [comment]
Thanks @rob-luke ! I see you even got the `maint` push. Hopefully the release process wasn't too much more complicated with the new infrastructure!

**Pull request merged**
