### PR TITLE
Birth Date Fix for SNIRF Files

### PR DESCRIPTION
**Pull request by chrsthur**
- Fixed metadata parameter requirements such that birth date is now optional

Linked Issue: SNIRF writer should not require birthdate #348

### CODE REVIEW

**Comment by rob-luke** [comment]
Hi @chrsthur, thanks for contributing this fix! Its greatly appreciated.

As a first time contributor GitHub will require me to authorise the CI runs. So feel free to @ my name if I need to click ok again.

Initial check of the code looks good. Lets see what the CIs say. Please ignore the numpydoc check, that's broken. The rest should come back with green ticks. If they dont, you can click on the details button and it will tell you what the error was.

Thanks again. Also FYI @dsleiter

**Comment by rob-luke** [comment]
@chrsthur I pushed a commit to your branch that added a test. This will ensure that we don't accidentally revert your change in the future. The only other thing was the lint check is failing. Otherwise looks good. Ping me when the style checks and test are green. Thanks

**Comment by rob-luke** [comment]
All green, thanks @chrsthur

**Comment by rob-luke** [comment]
And I have cut a new release of https://github.com/rob-luke/fnirs-apps-sourcedata2bids/releases/tag/v0.4.1

**Comment by dsleiter** [comment]
Looks great! Thanks, @chrsthur!

@rob-luke I did a quick review to see if there were any other optional SNIRF fields that the writer requires, and found two other potential cases, both for the probe.

1. `/nirs{i}/probe/sourceLabels` and `/nirs{i}/probe/detectorLabels` are optional. Currently those labels are parsed from `mne.io.Raw.ch_names`. Is there a possibility of channel names not existing in a `Raw` object containing fNIRS data?
2. the writer currently writes `/nirs{i}/probe/sourcePos3D` and `/nirs{i}/probe/detectorPos3D` and doesn't handle 2D positions. Is there ever a case where an `mne.io.Raw` fNIRS object would have 2D rather than 3D positions?

On a separate note: the SNIRF format says that the 2D positions are required while the 3D positions are optional. I had assumed that would be either/or situation, but perhaps it should be writing out 2D positions always (alongside the 3D positions if they exist). Do you think it is worth adding the 2D positions?

**Comment by rob-luke** [comment]
Thanks for checking @dsleiter 

> . Is there a possibility of channel names not existing in a Raw object containing fNIRS data

Not possible, so we are safe here

> Is there ever a case where an mne.io.Raw fNIRS object would have 2D rather than 3D positions?

Yeah the 2D requirement is because all the established labs used 2D positions. Currently if only 2d positions are available in the raw data, MNE will still store it as 3D internally and set z=0. So we could check if all(z==0) and then write to the 2D field in SNIRF. But I think we can just tackle that hurdle when we need to. If someone is only using 2D positions then they probably arent that serious about locations anyway.

I will raise this 2d requirment in the SNIRF repo, as i think its a bit odd

**Comment by dsleiter** [comment]
Ok, great. SNIRF might have a legacy reason for keeping the 2D positions around, but it would certainly be helpful if it was either/or.

**Pull request merged**
