### PR TITLE
MRG, MAINT: Faster CircleCI

### PR DESCRIPTION
**Pull request by larsoner**
An alternative solution to the doc-build issue @rob-luke -- just use `sphinx` directly. Not sure if the SMV_TAG_WHITELIST approach is better... but it's nice to be able to do `make html-single` locally, too, I think!

### CODE REVIEW

**Comment by larsoner** [comment]
15m total runtime, not too bad for building all the examples

**Comment by rob-luke** [comment]
My only hesitation is that now there is two methods for me to maintain, the multisphinx and plain sphinx, but thats manageable (with your help :wink: ).

Alternatively, it looks like github actions is going to work now with the 3d figures. So we could just delete circleci altogether?

**Comment by larsoner** [comment]
The big advantage of circle is that you can immediately view the artifact to see how it looks

**Comment by rob-luke** [comment]
> The big advantage of circle is that you can immediately view the artifact to see how it looks

Agreed. Lets proceed and merge this then. Thanks!

**Comment by larsoner** [comment]
... And you are already maintaining a plain sphinx build with the numpydoc target on actions :)

**Pull request merged**
