### PR TITLE
WIP: Add ability to use AR(N) noise models

### LINKED ISSUE #233: Add support for higher order AR noise models in run_GLM
#### Describe the new feature or enhancement
Add support for higher order AR noise models in the GLM. See https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4773699/#sec4title and   https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3756568/#sec3title for motivation.

#### Describe your proposed implementation
This will require modifying nilearn's GLM code to provide support for AR(N) models and has been started at... https://github.com/nilearn/nilearn/pull/2532

### PR DESCRIPTION
**Pull request by rob-luke**
Now that the nilearn modifications have been merged to master. Change the default behaviour in MNE-NIRS.

Closes #233 

- [x] Leave default noise_model as is.
- [x] Double check the recommendation from Huppert paper. I think it was Fs * 4.
- [x] Set new noise_model option of `auto`, which then auto calculates as above.
- [x] Add tests
- [x] Add example

### CODE REVIEW

**Comment by larsoner** [comment]
https://1135-254026779-gh.circle-artifacts.com/0/dev/master/auto_examples/general/plot_10_hrf_simulation.html#sphx-glr-auto-examples-general-plot-10-hrf-simulation-py is pretty cool / convincing that it does something sensible! Have you seen improvements in your own data? Might be a bit difficult to evaluate how much better it's doing without ground truth of some sort

**Comment by rob-luke** [comment]
Thanks for taking a detailed read @larsoner. I really like the idea of this approach (hence I invested so long in implementing it). I have been playing with this feature for almost a year now and have developed some opinions from many unstructured evaluations of this code, we can call if you want a detailed run down.

In short, my adhoc testing over the last year has shown no consistent benefit of using a higher order noise model, and that's why I left the default as AR(1). And I guess this is why the approach wasn't yet implemented in nilearn - it must not be standard in fMRI either.

I dug up some old figures from our NPH paper, in an early version I compared the effect of including different AR(N) models (the early version of the paper explored many more parameters, but I cut it down). From that data I saw little effect of using different noise models and two different sample rates. 

image

The other semi structured investigation I can quickly reproduce was to adjust the demos in this repo. The tapping data/task is the closest thing that I have to a ground truth with measured data, I expect a response to tapping and its always really large. The results from the individual example with AR(1) are...

(I mark the differences with a star *)
```text
                                se         theta Significant
                              mean          mean        mean
Condition     Chroma                                        
Control       hbo     1.084555e-06 -3.386871e-08        0.00
              hbr     6.083848e-07  1.348140e-08        0.00
Tapping/Left  hbo     1.100472e-06  6.898189e-06        0.90 *
              hbr     6.173233e-07 -3.039020e-06        0.75 *
Tapping/Right hbo     1.103144e-06  7.604877e-06        0.90
              hbr     6.188749e-07 -2.841256e-06        0.80
```

and with AR(4)

```text
                                se         theta Significant
                              mean          mean        mean
Condition     Chroma                                        
Control       hbo     1.251298e-06 -1.137739e-07        0.00
              hbr     5.342350e-07  1.167151e-08        0.00
Tapping/Left  hbo     1.265189e-06  7.539196e-06        0.85 *
              hbr     5.430301e-07 -2.957793e-06        0.80 *
Tapping/Right hbo     1.266834e-06  8.310573e-06        0.90
              hbr     5.446128e-07 -2.719418e-06        0.80
```

Looking at the group level analysis with AR(1):

```text
-----------------------------------------------------------------------------------------------------
                                                           Coef.  Std.Err.   z    P>|z| [0.025 0.975]
-----------------------------------------------------------------------------------------------------
ROI[Left_Hemisphere]:Condition[Control]:Chroma[hbo]        -0.286    1.793 -0.160 0.873 -3.800  3.227
ROI[Right_Hemisphere]:Condition[Control]:Chroma[hbo]       -0.884    1.793 -0.493 0.622 -4.397  2.630
ROI[Left_Hemisphere]:Condition[Tapping/Left]:Chroma[hbo]    1.964    1.793  1.096 0.273 -1.549  5.478
ROI[Right_Hemisphere]:Condition[Tapping/Left]:Chroma[hbo]  10.109    1.793  5.639 0.000  6.595 13.622
ROI[Left_Hemisphere]:Condition[Tapping/Right]:Chroma[hbo]   9.282    1.793  5.178 0.000  5.769 12.796
ROI[Right_Hemisphere]:Condition[Tapping/Right]:Chroma[hbo]  3.790    1.793  2.114 0.034  0.277  7.304
ROI[Left_Hemisphere]:Condition[Control]:Chroma[hbr]         0.269    1.793  0.150 0.881 -3.245  3.782
ROI[Right_Hemisphere]:Condition[Control]:Chroma[hbr]        0.140    1.793  0.078 0.938 -3.373  3.654
ROI[Left_Hemisphere]:Condition[Tapping/Left]:Chroma[hbr]   -2.004    1.793 -1.118 0.264 -5.518  1.509
ROI[Right_Hemisphere]:Condition[Tapping/Left]:Chroma[hbr]  -4.436    1.793 -2.474 0.013 -7.949 -0.922
ROI[Left_Hemisphere]:Condition[Tapping/Right]:Chroma[hbr]  -4.133    1.793 -2.306 0.021 -7.647 -0.620
ROI[Right_Hemisphere]:Condition[Tapping/Right]:Chroma[hbr] -1.960    1.793 -1.094 0.274 -5.474  1.553
```

and with AR(4)

```text
-----------------------------------------------------------------------------------------------------
                                                           Coef.  Std.Err.   z    P>|z| [0.025 0.975]
-----------------------------------------------------------------------------------------------------
ROI[Left_Hemisphere]:Condition[Control]:Chroma[hbo]        -0.354    1.751 -0.202 0.840 -3.787  3.079
ROI[Right_Hemisphere]:Condition[Control]:Chroma[hbo]       -0.842    1.751 -0.481 0.631 -4.274  2.591
ROI[Left_Hemisphere]:Condition[Tapping/Left]:Chroma[hbo]    1.875    1.751  1.071 0.284 -1.557  5.308
ROI[Right_Hemisphere]:Condition[Tapping/Left]:Chroma[hbo]   9.541    1.751  5.448 0.000  6.108 12.973
ROI[Left_Hemisphere]:Condition[Tapping/Right]:Chroma[hbo]   8.948    1.751  5.109 0.000  5.516 12.381
ROI[Right_Hemisphere]:Condition[Tapping/Right]:Chroma[hbo]  3.451    1.751  1.970 0.049  0.018  6.883
ROI[Left_Hemisphere]:Condition[Control]:Chroma[hbr]         0.250    1.751  0.143 0.886 -3.183  3.683
ROI[Right_Hemisphere]:Condition[Control]:Chroma[hbr]        0.112    1.751  0.064 0.949 -3.320  3.545
ROI[Left_Hemisphere]:Condition[Tapping/Left]:Chroma[hbr]   -1.968    1.751 -1.124 0.261 -5.401  1.465
ROI[Right_Hemisphere]:Condition[Tapping/Left]:Chroma[hbr]  -4.396    1.751 -2.510 0.012 -7.829 -0.964
ROI[Left_Hemisphere]:Condition[Tapping/Right]:Chroma[hbr]  -4.108    1.751 -2.346 0.019 -7.541 -0.675
ROI[Right_Hemisphere]:Condition[Tapping/Right]:Chroma[hbr] -1.914    1.751 -1.093 0.274 -5.347  1.518
```

I see no practical difference in the group results. The control conditions stays not significant. The p values for the active conditions seem to vary each way. Similarly in the individual results, HbO gets once less channel as significant for left tapping, and HbR gets one more significant channel. I have seen cases where there is a distinct difference in results and I am trying to determine why this happens in some studies (do some participants have more noise structure? or is the difference between results of AR(1) vs AR(4) larger when you have smaller responses? etc)  I plan to throw this general result as a subsection in to my next paper.

**Comment by rob-luke** [comment]
Running with an ols model does give a big difference (its worse, more false positive, less true positives)...

```text
                                se         theta Significant
                              mean          mean        mean
Condition     Chroma                                        
Control       hbo     1.749877e-06  8.864971e-07        0.35
              hbr     8.240692e-07 -6.989934e-07        0.20
Tapping/Left  hbo     1.772083e-06  7.820115e-06        0.85
              hbr     8.345270e-07 -1.357168e-06        0.45
Tapping/Right hbo     1.761802e-06  9.344735e-06        0.90
              hbr     8.296852e-07 -3.759559e-06        0.90
```

**Comment by rob-luke** [comment]
Actually I should write this properly as a letter.

**Comment by larsoner** [comment]
Nice analyses. I'll have to take a look with some of my data at some point to see if similar trends hold!

**Pull request merged**
