### PR TITLE
Import Gowerlabs data

### LINKED ISSUE #419: Read data from GowerLabs Lumo device in HDDOT format
#### Describe the new feature or enhancement
I would like to read data stored in the HDDOT format that was acquired using a GowerLab Lumo device.

The data format is described at: https://github.com/DOT-HUB/DOT-HUB_toolbox/blob/master/DOT-HUB_toolbox_Manual.pdf

Essentially:
* The data is in `.nirs` format (was the Homer data format, but now they move to SNIRF).
* Has a custom struct field for storing optode coordinates in 3D
* Stores the landmark coordinates for Nz, Iz, Ar, Lr, Cz

#### Describe your proposed implementation
1. Convert the `.nirs` file to `.snirf` using the Homer3 function `Nirs2Snirf.m`. By default Homer3 throws away the 3D coordinates, so you need to use my branch at: https://github.com/rob-luke/DataTree/tree/lumo
   This will produce a `.snirf` file but it loses the landmark positions, you need to write note these in the MATLAB command window.
2. Import the `snirf` file and then manually code in the landmark positions.

#### Describe possible alternatives

* It would be better if Homer3 `Nirs2Snirf.m`:
  1. Handled the 3D coordinates without using a custom branch, but I think the HDDOR SD3D structure is not standard?
  2. Did not throw away the landmarks and encoded them in the SNIRF file. [SNIRF can specify landmarks](https://github.com/fNIRS/snirf/blob/master/snirf_specification.md#nirsiprobelandmarklabelsj). 

* Write a `.nirs` reader. But this seems like lots of work and there is no specifications document and I think there are many versions running around. SNIRF was developed to overcome these problems.

#### Additional comments
Am I doing this correctly? How can we make this simpler?

### PR DESCRIPTION
**Pull request by rob-luke**
#### Reference issue
Closes #419 

#### What does this implement/fix?
Work in progress

#### Additional information
Work in progress

### CODE REVIEW

**Comment by rob-luke** [comment]
@samuelpowell could you (or someone else at Gowerlab) please review this PR.
You can [view the rendered document here](https://output.circle-artifacts.com/output/job/b8b8154a-00d9-44f3-b642-403bebc72c81/artifacts/0/html/auto_examples/general/plot_06_gowerlabs.html#sphx-glr-auto-examples-general-plot-06-gowerlabs-py).
I have also given you access to the branch so you can edit the document directly in the web interface.

If you have specific text changes you want then please edit the branch directly, or use the "add a suggestion" option in the code review (`Files Changed` tab). And we can expand the code too if there are some additional functionality that users often request.

And we should have a few more tutorials on analysis, but we need more extensive data for that.

**Comment by samuelpowell** [comment]
@rob-luke this is splendid thank you, we will review this week.

**Comment by rob-luke** [comment]
great @samuelpowell, and feel free to edit as much as you wish, the more information the better.
The formatting stuff can be fiddly, feel free to just get the text in there that you want and I can help with making sure it compiles without errors etc.

**Comment by samuelpowell** [comment]
@rob-luke just realised it’s a three day week owing to bank holidays so it will be next week before we can review, hope that’s alright.

**Comment by samuelpowell** [comment]
@nidadu could you add your suggestions inline on the web interface and I will go through and do a final clean and review?

**Comment by rob-luke** [comment]
> your suggestions inline on the web interface

You both have write access for the branch. So it may be more efficient to push your changes directly to the branch. Or do it via suggestions.

**Review by nidadu — CHANGES_REQUESTED** [review]
I have reviewed this tutorial and noted down some suggestions (mainly syntactic), @samuelpowell could you have a look please.

**Comment by samuelpowell** [comment]
Thanks @nidadu I'll merge whatever I'm qualified to merge, and make my own changes. @rob-luke we will ping you with any remaining queries once I've gone through this.

**Comment by rob-luke** [comment]
Thanks @nidadu 

The continuous integration ran so long ago that the page render has now been deleted. I'll kick the CI to make a fresh page render. Feel free to add reference articles or other useful links too. And we can always incrementally improve this page after it's merged.

**Comment by samuelpowell** [comment]
@rob-luke I'm happy with this. Please squash my untidy commits or ping me if you'd like me to do so!

**Comment by rob-luke** [comment]
This is great, thanks @samuelpowell and @nidadu.
Moving forward, feel free to propose updates and changes if you have further ideas or get feedback from users.

**Pull request merged**
