### PR TITLE
Try and fix pyvista figures with GitHub Actions

### PR DESCRIPTION
**Pull request by rob-luke**
I have split this issue off from #287. That PR highlighted that pyvista plotting works correctly on circleci, but all sphinx-gallery figures turn out as black squares when using GitHub Actions.  See previous discussion https://github.com/mne-tools/mne-nirs/pull/287#issuecomment-860561772 and https://github.com/mne-tools/mne-nirs/pull/287#issuecomment-860725288

I have confirmed this is not a issue with pyvista running on GitHub Actions. See point 3 below.

1. In the CircleCI you can see the correct figure is presented at the bottom of this page. https://1282-254026779-gh.circle-artifacts.com/0/dev/pull/297/auto_examples/general/plot_01_data_io.html#custom-data-import
2. However, in the GitHub Actions build it is just a black square. You can see this by downloading the documentation artefact from the build at https://github.com/mne-tools/mne-nirs/pull/297/checks?check_run_id=2827440875 and going to `refs-11/pull/297/merge/auto_examples/general/plot_01_data_io.html`
3. To check that GitHub Actions has pyvista installed correctly I have added a minimal pyvista command to the GitHub action, and it correctly generates a 3d figure. See the screenshot artefacts in the above action. And https://github.com/pyvista/test-pyvista-gh-action/pull/3

### CODE REVIEW

**Comment by rob-luke** [comment]
@GuillaumeFavelier do you have any suggestions as to what else I can investigate to find the underlying issue here?

**Comment by GuillaumeFavelier** [comment]
Hm... The plots of the pyvista 3d backend use `PyQt5` so I would remove:

```
      PYVISTA_OFF_SCREEN: True
      PYVISTA_USE_IPYVTK: True
```

because AFAIK, true `off_screen` rendering is not supported with `PyVistaQt`.

Also I see that you test the standard `Plotter` of PyVista (which is used only by the `notebook` 3d backend) but testing `BackgroundPlotter` might be a better test. Something like:

```
python -c "import pyvistaqt; pyvistaqt.BackgroundPlotter(show=True)"
```

From `mne-python`: https://github.com/mne-tools/mne-python/blob/main/.circleci/config.yml#L125

Sorry if my comments are confusing, I can clarify if you have a question

**Comment by rob-luke** [comment]
Thanks for taking a look @GuillaumeFavelier. I removed `PYVISTA_OFF_SCREEN` and `PYVISTA_USE_IPYVTK`  as you suggested, and added `python -c "import pyvistaqt; pyvistaqt.BackgroundPlotter(show=True)"` as test. However, the pyvista figures are still rendering as just black. I noticed you had some success over at https://github.com/ja-che/hidimstat/pull/25, do you have any additional suggestions based on that PR as to what I might look further in to?

**Comment by GuillaumeFavelier** [comment]
> I noticed you had some success over

I'm sorry @rob-luke, it ended up being a failure. I basically just reproduced the issue of this PR. As of now, I still do not have a clear idea of causes this.

I can only focus on the differences between the Circle env and GitHub Actions/Ubuntu :thinking:

**Comment by rob-luke** [comment]
Thanks for letting me know @GuillaumeFavelier, I might put this on hold then and just not demo the 3d functionality.

Thanks for the help! 🙏

**Comment by GuillaumeFavelier** [comment]
I created https://github.com/GuillaumeFavelier/pyvista_github_actions to continue to investigate independently of `mne-nirs`.

**Comment by GuillaumeFavelier** [comment]
From I can see from the [generated artifacts](https://github.com/GuillaumeFavelier/pyvista_github_actions/actions/runs/990174072), it works for basic pyvista/pyvistaqt so I can only narrow the research on `plot_stc/brain_scraper`.

**Comment by rob-luke** [comment]
THANK YOU @GuillaumeFavelier!! I will follow you in your new repo

**Pull request closed without merging**
