### PR TITLE
Add bug fix from #349 to changelog

### PR DESCRIPTION
**Pull request by rob-luke**
@chrsthur is this ok with you? I forgot to add it in your PR.

### CODE REVIEW

**Comment by chrsthur** [comment]
Looks good to me!

**Comment by rob-luke** [comment]
Is this ok @chrsthur? Feel free to suggest changes using the GitHub interface if you want changes.

**Comment by rob-luke** [comment]
bump @chrsthur

**Comment by chrsthur** [comment]
Hello Rob,
Sorry, I saw this a while ago but forgot to reply. Looks good to me! Thanks for adding them to the changelog.

**Comment by rob-luke** [comment]
> Thanks for adding them to the changelog.

No, thank you for the bug fix!

**Pull request merged**
