### PR TITLE
Update environment and requirements to match MNE

### PR DESCRIPTION
**Pull request by rob-luke**

### CODE REVIEW

**Comment by rob-luke** [comment]
Fails on linux with 

```bash
E ImportError: libGLX.so.0: cannot open shared object file: No such file or directory
```

**Comment by larsoner** [comment]
The advantage of using a config like MNE-Python is that you can benefit from our fixes, `meld` or do a similar diff whenever you see problems like this and hopefully this would pop up as a candidate:

https://github.com/mne-tools/mne-python/blame/master/.circleci/config.yml#L58

In this case it's probably `libglx0`. FYI this is really a VTK bug that they're in the process of fixing but did not make it into the 9.0.0 wheels

**Comment by larsoner** [comment]
Oh sorry this is Travis not CircleCI, but the fix is similar

https://github.com/mne-tools/mne-python/blame/master/.travis.yml#L12

**Comment by larsoner** [comment]
(Or you could subscribe to all MNE-Python updates, but then you will have the same painful email load as @agramfort :) )

**Comment by rob-luke** [comment]
> Or you could subscribe to all MNE-Python updates

Haha i do. Thats how I saw that MNE had updated pyvista and thats what inspired this change here.

> The advantage of using a config like MNE-Python is that you can benefit from our fixes, meld 

Thanks, I need to get my tooling better. I should have some assisted way of tracking changes in relevant MNE files so I don't need to do this manually. Maybe once the API settles and this is totally usable Ill then get around to it.

> Oh sorry this is Travis not CircleCI, but the fix is similar

Thank you! Appreciate the pointer

**Pull request merged**
