### PR TITLE
Remove mayavi from requirements

### PR DESCRIPTION
**Pull request by rob-luke**
Follows #365 as the maintenance upkeep is too much for me.

### CODE REVIEW

**Comment by rob-luke** [comment]
Breaks more than it fixes. Cancelling.

**Comment by agramfort** [comment]
interesting attempt. What does it break? you should also remove pysurfer that requires mayavi. We will want to do this soon

**Comment by rob-luke** [comment]
Only circle ci broke. GH actions worked. As this is useful to others too I will try this again then. Starting with your suggestion. Then maybe this will help when you get around to it too.

**Comment by rob-luke** [comment]
Thanks @agramfort now it works. I checked the CircleCI docs and the renders still look good, so nothing seems broken. Cheers.

**Pull request merged**
