### PR TITLE
MAINT: Update for Hitachi

### PR DESCRIPTION
**Pull request by larsoner**
Use newer method for verifying freqs to avoid:
```
  File "<decorator-gen-528>", line 22, in peak_power
  File "/home/larsoner/python/mne-nirs/mne_nirs/preprocessing/_peak_power.py", line 65, in peak_power
    picks = _check_channels_ordered(raw.info, freqs)
  File "/home/larsoner/python/mne-python/mne/preprocessing/nirs/nirs.py", line 159, in _check_channels_ordered
    raise ValueError(
ValueError: NIRS channels not ordered correctly. Channels must be ordered as source detector pairs with alternating frequencies: 698 & 699
```

### CODE REVIEW

**Comment by rob-luke** [comment]
@larsoner any idea why the tests and docs froze on `Show infos` after 5 hour run time?

**Comment by rob-luke** [comment]
Other than that it looks great!

**Comment by larsoner** [comment]
Probably the VTK 9.0.2 wheels, I'd pin to `<=9.0.1` for now

**Comment by rob-luke** [comment]
> Probably the VTK 9.0.2 wheels, I'd pin to `<=9.0.1` for now

Thanks. Its happening in my other branches too. Ill try your suggestion

**Comment by rob-luke** [comment]
See #307

**Comment by rob-luke** [comment]
Thanks @larsoner

**Pull request merged**
