### PR TITLE
Add glm.save and read_glm

### LINKED ISSUE #116: Demonstrate how to save analysis and resume
> Do you want to update a MNE-nirs example to show how you envision users using this API / saving to get back to an analysis / coefficients that they previously computed? https://github.com/mne-tools/mne-nirs/pull/111#issuecomment-643837608

with some greater pointers from larsoner here  https://github.com/mne-tools/mne-nirs/pull/111#issuecomment-643613639

### PR DESCRIPTION
**Pull request by rob-luke**
Closes #116

Implement a method to write GLM results to disk and read them back.
Handles the wrangling of nested types.

- [x] Confirm the approach taken is reasonable
- [x] ~~Is there a way to test if two objects are the same? Currently I test if the resulting dataframe is identical.~~ I added an `__eq__` method.
- [x] Also implement for ContrastResults
- [x] Add more tests specifically checking types:
  - [x] ContrastResults, OLSModel
- [x] Add tutorial

### CODE REVIEW

**Comment by rob-luke** [comment]
@larsoner could you please give this a review? (The numpydoc failure is existing issue). There is quite some data wrangling, so maybe an easier solution exists.

**Comment by rob-luke** [comment]
Here is the tutorial render as i never solved the linking issue https://1580-254026779-gh.circle-artifacts.com/0/dev/pull/337/auto_examples/general/plot_80_save_read_glm.html#sphx-glr-auto-examples-general-plot-80-save-read-glm-py

**Comment by larsoner** [comment]
The approach seems reasonable to me, we do something similar for saving and loading dipy classes in MNE-Python

**Comment by rob-luke** [comment]
Appreciate you looking @larsoner. I'll check out the dipy code you mention. And then push on with this.

**Comment by larsoner** [comment]
That code lives in mne/morph.py. we also use a state-based approach in csd.py I think

**Pull request merged**
